# https://arduino.github.io/arduino-cli/latest/library-specification/
name=Decept
version=0.1.0-snapshot
author=Shawn Silverman <shawn@pobox.com>
maintainer=Shawn Silverman <shawn@pobox.com>
sentence=A hardware-based crypto library for Teensy 4.
paragraph=Other algorithms are added on top of the base features, for example, HMAC, TOTP, and various DRBG implementations.
category=Data Processing
url=https://github.com/ssilverman/Decept
architectures=*
includes=Decept.h
